django_instagram/django_instagram/urls.py
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from .views import *
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/',include('post.urls',namespace='post')),
    url(r'^accounts/',include('django.contrib.auth.urls',namespace='account')),
    # django/contrib/auth/urls.py app_name ='account'
    # Reverse for 'password_change_done' not found. 'password_change_done' is not a valid view function or pattern name.
    # solve : path('password_change/', views.PasswordChangeView.as_view(success_url=reverse_lazy('account:password_change_done')), name='password_change'),
    url(r'^$',Main.as_view(),name='main'),
    url(r'',include('social_django.urls',namespace='social'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

django_instagram/post/urls.py
from django.conf.urls import url
from post.views import *
app_name = 'post'
urlpatterns = [
    url(r'^$',post_list,name='post_list'),
    url(r'^profile/edit/$',profile_update,name='profile_update'),
    url(r'^new/$', Post_create.as_view(), name='post_create'),
    url(r'^modification/(?P<pk>\d+)/$', post_update, name='post_update'),
    url(r'^delete/(?P<pk>\d+)/$', post_delete, name='post_delete'),
    url(r'^(?P<pk>\d+)/$', post_detail, name='post_detail'),
    url(r'^(?P<author>\w+)/$',user_post,name='user_post_list'),
    url(r'^(?P<author>\w+)/follow/$', post_follow, name='follow'),
    url(r'^(?P<pk>\d+)/like/$',post_like,name='like'),
    url(r'^search',post_search,name='search'),
    url(r'^tag/(?P<tag>\w+)/$',tag_list,name='tag_list'),
    url(r'^reple/(?P<pk>\d+)/$', post_reple, name="post_reple"),
    url(r'^reples/(?P<pk>\d+)/$', more_reples, name="more_reples"),
    url(r'^follow/list/$',follow_request_list,name="follow_request_list")
]

django_instagram/templates/base_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>instagram</title>
    {% load staticfiles %}
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}"/>
    <link rel="stylesheet" href="{% static 'css/common.css'%}">
    <link rel="stylesheet" href="{% static 'css/base_home.css' %}">
    <link rel="stylesheet" href="{% block extrastyle %}{% endblock %}">
</head>
<body>

    <div id="wrap">
        <header>
            <div>
                <h1><a href="{% url 'post:post_list' %}"></a></h1>
                <ul id="search">
                    <li>
                        <input type="text" placeholder="검색" id="search-form">
                        <div class="search-list-field">
                            <ul id="search-list">
                            </ul>
                        </div>
                    </li>
                </ul>
                <ul id="nav-list">
                    <li><a href="{% url 'post:post_create' %}"></a></li>
                    <li>
                        <span></span>
                        <ul class="follower-request d_n">
                            {% load custom_tags %}
                            <li><p>팔로워 요청&nbsp;<span><a href="{% url 'post:follow_request_list' %}">{% follower_request user as count %} {{ count }} 건</a></span></p></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'post:user_post_list' user.username %}"></a></li>
                </ul>
            </div>
        </header>
        <section>
            <article>
                {% block content %}
                {% endblock %}
            </article>
        </section>
        <footer>

        </footer>
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static 'js/common.js' %}"></script>
    <script>
    $("#search-form").change(function(){
            $("#search-list").html("");
            var word = $(this).val();
            if(word==""){
                return;
            }else{
                var url;
                var user_post;
                $.ajax({
                    url:'{% url "post:search" %}',
                    data:{
                        'word':word
                    },
                    dataType:'json',
                    success:function(data){
                        if(data.flag){
                            $(".search-list-field").css("display","block");
                            if(data.data) {
                                for (var i = 0; i < data.data.length; i++) {
                                    user_post = data.data[i].username;
                                    url = "{% url 'post:user_post_list' 1234 %}".replace(/1234/, user_post.toString());
                                    $("#search-list").append(
                                         "<li><div class='profile-img'><img src='/media/" + data.profile[i]['avatar'] + "'></div><div class='profile-name'><a href=" + url + " class='user-post-list-link'>" + data.data[i]['username'] + "</a></div></li>"
                                    );
                                }
                            }
                            if(data.tag){
                                url = "{% url 'post:tag_list' 1234%}".replace(/1234/,data.tag);
                                $("#search-list").append(
                                        "<li><div class='tag-icon'><div></div></div><div class='tag-name'><a href=" + url + " class='user-post-list-link'>#" + data.tag + "</a></div><div class='tag-count'>"+data.tag_count+"개의 글</div></li>"
                                    );
                                }
                        }else{
                            $(".search-list-field").css("display","none");
                        }
                    }
                });
            }
        });
        $("#nav-list > li:nth-child(2) > span").on("click",function(){
            $(".follower-request").toggleClass('d_n');
            $(".follower-request").toggleClass('d_b');
        });
    {% block javascript %}
    {% endblock %}</script>
</body>
</html>

django_instagram/templates/base_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>instagram</title>
    {% load staticfiles %}
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}"/>
    <link rel="stylesheet" href="{% static 'css/base_main.css' %}">
    <link rel="stylesheet" href="{% block extrastyle %}{% endblock %}">
</head>
<body>
{% if user.is_anonymous %}
 <div id="wrap">
        <header>
            <h1><a href="{% url 'main' %}">Instagram</a></h1>
        </header>
        <section>
            <article>
                <div class="phone-img">
                    <img src="{% static 'img/iphone.PNG' %}" alt="iphone">
                </div>
                    {% block content %}
                    {% endblock %}
            </article>
        </section>
        <footer>
            <p>made by leeyejin &nbsp;<a href="https://github.com/lowelllll"><img src="{% static 'img/logo.png' %}" alt="git-logo"></a></p>
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="{% static 'js/common.js' %}"></script>
    <script>
    {% block javascript %}
    {% endblock %}</script>

</body>
</html>
{% else %}
    <script>
        location.href={% url 'post:post_list' %};
    </script>
{% endif %}