django_instagram/django_instagram/urls.py
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from .views import *
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/',include('post.urls',namespace='post')),
    url(r'^accounts/',include('django.contrib.auth.urls',namespace='account')),
    # django/contrib/auth/urls.py app_name ='account'
    # Reverse for 'password_change_done' not found. 'password_change_done' is not a valid view function or pattern name.
    # solve : path('password_change/', views.PasswordChangeView.as_view(success_url=reverse_lazy('account:password_change_done')), name='password_change'),
    url(r'^$',Main.as_view(),name='main'),
    url(r'',include('social_django.urls',namespace='social'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

django_instagram/post/urls.py
from django.conf.urls import url
from post.views import *
app_name = 'post'
urlpatterns = [
    url(r'^$',post_list,name='post_list'),
    url(r'^profile/edit/$',profile_update,name='profile_update'),
    url(r'^new/$', Post_create.as_view(), name='post_create'),
    url(r'^modification/(?P<pk>\d+)/$', post_update, name='post_update'),
    url(r'^delete/(?P<pk>\d+)/$', post_delete, name='post_delete'),
    url(r'^(?P<pk>\d+)/$', post_detail, name='post_detail'),
    url(r'^(?P<author>\w+)/$',user_post,name='user_post_list'),
    url(r'^(?P<author>\w+)/follow/$', post_follow, name='follow'),
    url(r'^(?P<pk>\d+)/like/$',post_like,name='like'),
    url(r'^search',post_search,name='search'),
    url(r'^tag/(?P<tag>\w+)/$',tag_list,name='tag_list'),
    url(r'^reple/(?P<pk>\d+)/$', post_reple, name="post_reple"),
    url(r'^reples/(?P<pk>\d+)/$', more_reples, name="more_reples"),
    url(r'^follow/list/$',follow_request_list,name="follow_request_list")
]

django_instagram/post/models.py
# -*- coding:UTF-8 -*-
from django.db import models
from django.conf import settings
from django.urls.base import reverse
from django.utils.encoding import python_2_unicode_compatible
# Create your models here.
@python_2_unicode_compatible
class Tag(models.Model):
    tag = models.CharField(max_length=20)

    def __str__(self):
        return self.tag

@python_2_unicode_compatible
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='post/%Y/%m')
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('post:post_detail',args=[self.id])

@python_2_unicode_compatible
class Reple(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    author_name = models.CharField(null=True, max_length=200)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True, null=True)  # 생성했을 때

    class Meta:
        ordering = ['-date']
    def __str__(self):
        return self.content


@python_2_unicode_compatible
class Follow(models.Model):
    folloing = models.CharField(max_length=200)  # 팔로우 한 사람
    follower = models.CharField(max_length=200)  # 팔로우 당한 사람

    def __str__(self):
        return self.folloing

@python_2_unicode_compatible
class Like(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

django_instagram/post/forms.py
from django import forms
from accounts.models import Profile
from post.models import Post

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar',)

class RepleForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea,max_length=200)

class SearchForm(forms.Form):
    word = forms.CharField(max_length=50)

class PostForm(forms. ModelForm):
    class Meta:
        model = Post
        fields = ('content','image',)

django_instagram/post/views.py
# -*- coding:UTF-8 -*-
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.urls.base import reverse_lazy
from django.contrib.auth import get_user_model
from .models import *

from django.conf import settings
from .forms import *
import datetime
from django.http import JsonResponse
from django.db.models import Q
import re

# Create your views here.
@login_required()
def post_list(request):
    follows = Follow.objects.filter(folloing=request.user.username).values('follower')
    posts = Post.objects.select_related('author__profile').prefetch_related('reple_set', 'reple_set__author',
                                                                            'like_set').filter(Q(author__username__in=follows)|Q(author=request.user)) # or은 Q 객체를 사용해야함.
    return render(request, 'post/post_list.html', {'posts':posts, 'date':datetime.datetime.now()})

@login_required()
def profile_update(request):
    if request.method=='POST':
        form = ProfileForm(request.POST,request.FILES,instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('post:post_list')
    else:
        form = ProfileForm(instance=request.user.profile)
    return render(request,'post/profile_form.html',context={'form':form})

class Post_create(CreateView,LoginRequiredMixin):
    model = Post
    success_url = reverse_lazy('post:post_list')
    fields = ['content','image']
    def form_valid(self, form):
        form.instance.author = self.request.user
        post = form.save(commit=False)
        post.save()
        tags = tag_create(self.request.POST['content'])
        post.tags.add(*tags)  # list 저장하기 위해 * 붙여줌
        post.save()
        return HttpResponseRedirect(self.success_url)

@login_required()
def post_update(request,pk):
    p = get_object_or_404(Post,pk=pk)
    if request.user != p.author:
        return HttpResponse("<script>alert('잘못된 접근입니다.'); history.back();</script>")

    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES,instance=p)
        if form.is_valid():
            post = form.save()
            post.tags.all().delete()
            tags = tag_create(request.POST['content'])
            post.tags.add(*tags)  # list 저장하기 위해 * 붙여줌
            post.save()
            return redirect("post:post_detail",post.pk)
    else:
        form = PostForm(instance=p)
    return render(request,"post/post_form.html",{'form':form})

@login_required()
def post_delete(request,pk):
    p = get_object_or_404(Post,pk=pk)
    if request.user!= p.author:
        return HttpResponse("<script>alert('잘못된 접근입니다.'); history.back();</script>")
    p.delete()
    return redirect("post:post_list")

@login_required()
def post_detail(request,pk):
    post = Post.objects.select_related("author__profile").get(id=pk)
    reple_list = Reple.objects.filter(post=pk).select_related("author")
    is_like = Like.objects.filter(post=post,user=request.user).exists()
    like = Like.objects.filter(post=post)
    context = {
        'post': post,
        'reple_list': reple_list,
        'is_like': is_like,
        'like': like
    }
    return render(request,'post/post_detail.html',context)

@login_required()
def user_post(request,author):
    User = get_user_model()
    user = User.objects.get(username=author)
    folloing = Follow.objects.filter(folloing=author).count()
    follower = Follow.objects.filter(follower=author).count()
    posts = Post.objects.prefetch_related('reple_set','like_set').filter(author=user)
    is_follow = Follow.objects.filter(follower=author,folloing=request.user).exists() # 해당 객체가 있으면 True,없으면 False 리턴
    context = {
        'posts':posts,
        'author':user,
        'is_follow':is_follow,
        'folloing':folloing,
        'follower':follower
    }
    return render(request,'post/user_post_list.html',context)


@login_required()
def post_follow(request, author):
    follow, flag = Follow.objects.get_or_create(follower=author, folloing=request.user)
    if not flag:  # 원래 객체가 존재했다면
        follow.delete()
        message = "folloing"
        message_kr = "팔로잉"
    else:
        message = "follow"
        message_kr = "팔로우"

    follow_count = Follow.objects.filter(follower=author).count()
    data = {
        'follow_count': follow_count,
        'message': message,
        'message_kr':message_kr
    }
    return JsonResponse(data)


@login_required()
def post_like(request,pk):
    post = Post.objects.get(pk=pk)
    like,flag = Like.objects.get_or_create(post=post,user=request.user)
    if not flag:
        like.delete()
        message = 'like'
    else:
        message = 'liked'
    like_count = Like.objects.filter(post=post).count()
    data = {
        'message':message,
        'like_count':like_count
    }
    return JsonResponse(data)

@login_required()
def post_search(request):
    word  = request.GET.get('word', None)
    User = get_user_model()
    data = {}
    data['flag'] = False
    try:
        users = User.objects.filter(
            Q(username__icontains=word)
        ).values()
        profiles = Profile.objects.filter(
            Q(user__username__icontains=word)
        ).values()
        if users:
            data['flag'] = True
            data['profile'] = list(profiles)
            data['data'] = list(users)
    except:
        pass
    try:
        tag = Tag.objects.get(tag=word)
        data['tag'] = tag.tag
        data['tag_count'] = tag.post_set.count()
        data['flag']= True
    except:
        pass
    finally:
        return JsonResponse(data)

@login_required()
def tag_list(request,tag):
    t = Tag.objects.get(tag=tag)
    posts = t.post_set.all()
    return render(request,'post/tag_list.html',{'posts':posts,'tag':tag})

def tag_create(content):
    find_tags = "".join(re.findall('#\w{0,20}\s', content))
    find_tags = re.sub("\s", "", find_tags)
    temp_tags = re.split("#", find_tags)
    tags = []
    for temp_tag in temp_tags:
        if temp_tag == '':
            continue
        else:
            tag, flag = Tag.objects.get_or_create(tag=temp_tag)
            tags.append(tag)
    return tags

@login_required()
def post_reple(request,pk):
    try:
        post = Post.objects.get(pk=pk)
        comment = request.GET.get('comment')
        reple = Reple(author = request.user , post=post,content=comment,author_name=request.user.username)
        reple.save()
        data = {
            'reple':reple.content,
            'author':reple.author.username,
            'flag':True
        }
        return JsonResponse(data)
    except:
        data = {
            'flag':False
        }
        return JsonResponse(data)

@login_required()
def more_reples(request,pk):
    data = {}
    try:
        post = Post.objects.get(pk=pk)
        reples = post.reple_set.all().values().reverse()
        data['reples'] = list(reples)
    except:
        print("error")
    finally:
        return JsonResponse(data)

@login_required()
def follow_request_list(request):
    try:
        followers = Follow.objects.filter(follower=request.user.username)  # 나를 팔로워 한 사람들
        folloings = Follow.objects.filter(folloing=request.user.username).values('follower')  # 내가 팔로워 한 사람들
        follow_list = followers.exclude(folloing__in=folloings)
        # follow_list_values = followers.exclude(folloings__in=folloings)
        # User = get_user_model()
        # follow_users = User.objects.filter(username__in=follow_list_values).select_related('profile')
        context = {
            'follow_list':follow_list
        }
        return render(request,'post/follow_request_list.html',context)
    except:
        return

django_instagram/post/templates/post/follow_request_list.html
{% extends 'base_home.html' %}
{% load staticfiles %}
{% block extrastyle %}{% static 'css/follow_request.css' %}{% endblock %}
{% block content %}
<div class="folloing-area">
    <h1>팔로잉 요청 목록</h1>
    <p>{{ follow_list|length }}개의 요청</p>
</div>
<div class="user-list">
    <ul>
        {% for follow in follow_list %}
        <li>
            <p><a href="{% url 'post:user_post_list' follow.folloing %}">{{ follow.folloing }}</a></p>
            <button class="un_follow" id="follow" value="{{ follow.folloing }}">팔로잉</button>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}
{% block javascript %}
// 팔로우 기능
$(".un_follow").on("click",function(){
    $this = $(this);
    var user = $(this).attr("value");
    var url = "{% url 'post:follow' 1234 %}".replace(/1234/,user);
    $.ajax({
        url:url,
        dataType:'json',
        success: function(data){
            $this.text(data.message_kr);
            $this.attr("class",data.message);
        }
});
});
{% endblock %}

django_instagram/post/templates/post/post_detail.html
{% extends 'base_home.html' %}
{% load staticfiles %}
{% block extrastyle %}{% static 'css/post_detail.css' %}{% endblock %}
{% load custom_tags %}
    {% block content %}
    <div id="config_option">
        <ul>
            <li><a href="{% url 'post:post_update' post.id %}">수정</a></li>
            <li><a href="{% url 'post:post_delete' post.id %}">삭제</a></li>
        </ul>
    </div>
   <div class="post-img"><img src="{{ post.image.url }}" alt="img-content"></div>
                <div class="post-content">
                    <div class="post-header">
                        <div><img src="{{ post.author.profile.avatar.url }}" alt="{{ post.author }}"></div>
                        <p><a href="{% url 'post:user_post_list' post.author.username %}">{{ post.author }}</a></p>
                    </div>
                    <div class="post-text-reple-area-wrap">
                        <!--scroll 없애기-->
                        <div class="post-text-reple-area">
                            <div class="post-text">
                                <p><span>{{ post.author }}&nbsp;</span>{{ post.content|tag_link:post }}</p>
                            </div>
                            <div class="post-reples">
                                {% for reple in reple_list reversed %}
                                 <p><span>{{ reple.author }}&nbsp;</span>{{ reple.content }}</p>
                        {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="post-button">
                         <button type="button"  id ="like-button"class=" {% if is_like %}liked"{% else %}like"{% endif %}></button>
                        <button type="button" id="reple-button">
                    </div>
                    <p class="like-count">
                        좋아요 {{ post.like_set.count }}개
                    </p>
                    <p class="post-date">
                       {{ post.date }}
                    </p>
                    <div id="reple-form">
                        <input type="text" placeholder="댓글 달기..">
                        {% if post.author == user %}<span><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE1SURBVGhD7dnNKkVRGMbxbeYrRoww4k6Q8lVuBOUadIYmcg9EkeJCRPm4DQrh/9TatVotjNR69P7rN1n7TN6zzz671uqiKIqi1Dj2cJHspjWrpnGHz8ItpmDTGcoheiewaBLvqA0hb5hA882jNkBOn2m+UTyjNoDo2jAsOkRtCDmATborVyiHuISu2bWE/WRRC1EURc03m9i2iSf075BHrMOqLXwgfxmK1jZgk779coierlk0h9oAOYtn5t8Mon76ad3DJv1jffewr8Iq/dXmd+YBa7BtJomiKGq7IaxgkCynNau05XON/GUo2iKy2g46QjlET5t3Fo3hBbUhRFumI2i+BdQGyFlsYv92rPAKi2MFdYraEHIMm3S8pmO2cogbWB29KR187uA82YbFQx5FUfTXdd0XjeeiCFjZX5QAAAAASUVORK5CYII="></span>  {% endif %}
                    </div>
                </div>

{% endblock %}
{% block javascript %}
$("#like-button").on("click",function(){
    $.ajax({
        url:'{% url 'post:like' post.id %}',
        dataType:'json',
        success:function(data){
            $(".like-count").text("좋아요 "+data.like_count+"개");
            $("#like-button").attr("class",data.message);
        }
    });
});
$("#reple-form > input").keyup(function(e) {
    if (e.keyCode == 13) {
        // enter 를 눌렀을때
        var $this = $(this);
        var comment = $this.val();
        var url = "{% url 'post:post_reple' 1234%}".replace(/1234/,{{ post.pk }});
        $.ajax({
            url:url,
            data:{
                'comment':comment
            },
            dataType:'json',
            success:function(data){
                $this.val("");
                 $(".post-reples").append("<p><span>"+data.author+"</span> "+data.reple+"</p>");
            }
        });

    }
});
$("#reple-button").on("click",function(){
    $("#reple-form > input").focus();
});
$("#reple-form span").on("click",function(){
    $("#config_option").css("display","block");
});
$("#config_option").on("click",function(){
    $(this).css("display","none");
})
{% endblock %}

django_instagram/post/templates/post/post_form.html
{% extends 'base_home.html' %}
{% load staticfiles %}
{% block extrastyle %}{% static 'css/post_form.css' %}{% endblock %}
{% block content %}
<div class="post-form">
                    <form action="." method="post" enctype="multipart/form-data">{% csrf_token %}
                        {% if forms.errors %}
                             <script>
                                alert("게시글 업로드에 실패했습니다. 다시 입력해주세요.");
                            </script>
                            {% endif %}
                        <div class="post-img">
                            <div></div>
                                <img src="" alt="img" id="blah">
                        </div>
                        <div class="post-file">
                            {% if form.image.value %}
                                {{ form.image }}
                            {% else %}
                                <input type="file" name="image" id="id_image" required>
                            {% endif %}
                        </div>
                        <div class="post-content">
                                <textarea name="content" id="id_content" cols="30" rows="10" required placeholder="이미지는 가능한 정사각형으로 올려주세요. &#13;&#10;#태그명 으로 태그 등록이 가능합니다.(띄어쓰기 해야함.)">{% if form.content.value %}{{ form.content.value }}{% endif %}</textarea>
                        </div>
                        <div class="post-button">
                            <input type="submit" value="저장">
                        </div>
                    </form>
</div>
{% endblock %}
{% block javascript %}
// 이미지 미리보기
 $(function() {
            $("#id_image").on('change', function(){
                readURL(this);
            });
        });

        function readURL(input) {
            if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                    $('#blah').attr('src', e.target.result);
                }

              reader.readAsDataURL(input.files[0]);
            }
        }
{% endblock %}

django_instagram/post/templates/post/post_list.html
{% extends 'base_home.html' %}
{% load staticfiles %}
{% block extrastyle %}{% static 'css/post_list.css' %}{% endblock %}
{% load custom_tags %}
{% block content %}
<div class="posts">
    {% if posts %}
    {% for post in posts %}
    <div class="post">
        <div class="post-header">
            <div><img src="{{ post.author.profile.avatar.url }}" alt=""></div>
            <p class="post-profile-name"><b><a href="{% url 'post:user_post_list' post.author %}">{{ post.author }}</a></b></p>
        </div>
        <div class="post-img">
            <a href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }}" alt="img"></a>
        </div>
        <div class="post-info">
            <div class="post-like-reple-bar">
                {% is_likes post request.user as is_like %}
                 <button type="button"  value="{{ post.id }}" class="like-button {% if is_like %}liked"{% else %}like"{% endif %}></button>
                <span class="reple-pointer" value="{{ post.id }}"></span>
            </div>
            <div class="post-like-count">
                <p class="like-count-{{ post.id }}">좋아요 {{ post.like_set.count }}개</p>
            </div>
            <div class="post-content">
                <p><span>{{ post.author }}&nbsp;</span>{{ post.content|tag_link:post }}</p>
            </div>
            <div class="post-reple-list reple-list-{{ post.id }}">
                {% if post.reple_set.all|length > 3 %}
                <p><span class="more-reples" value="{{ post.id }}">댓글 더보기</span></p>
                {% endif %}
                <div>
                    {% for reple in post.reple_set.all|slice:":3" reversed %}
                        <p><span>{{ reple.author.username }} &nbsp;</span>{{ reple.content }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="date">
                <p>{{ post.date|post_date }}</p>
            </div>
            <div class="post-reple-form">
                <input type="text" placeholder="댓글쓰기.." name="reple" class="reple-content-{{ post.id }}"><button type="button" value="{{ post.id }}">게시</button>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
</div>
<div class="aside">
    <div class="user-profile">
        <div><img src="{{ user.profile.avatar.url }}" alt="avatar"></div><p>{{ user.username }}</p>
    </div>
    <div class="developer-info">
        <a href=""><img src="" alt=""></a>
    </div>

</div>
{% endblock %}
{% block javascript %}
/* 좋아요 AJAX */
$(".like-button").on("click",function(){
    var pk = $(this).attr("value");
    var url = "{% url 'post:like' 1234 %}".replace(/1234/,pk);
    var $this = $(this);
    $.ajax({
        url:url,
        dataType:'json',
        success:function(data){
            $(".like-count-"+pk).text("좋아요 "+data.like_count+"개");
            $this.attr("class",data.message+" like-button");
        }
    })
});

/* 댓글 달기 AJAX */
$(".post-reple-form > button").on("click",function(){
    var pk = $(this).attr("value");
    var $repleContent = $(".reple-content-"+pk);
    var comment = $repleContent.val();
    $repleContent.val("");
    var url = "{% url 'post:post_reple' 1234 %}".replace(/1234/,pk);
    $.ajax({
        url:url,
        data:{
            'comment':comment
        },
        dataType:'json',
        success:function(data){
            //console.log(data.flag);
            //console.log(pk);
            $(".reple-list-"+pk).append("<p><span>"+data.author+"&nbsp</span>"+data.reple+"</p>");

        }
    })
});

/* 댓글 더보기 AJAX */
$(".more-reples").on("click",function(){
    var $this = $(this);
    var pk = $(this).attr("value");
    var url = "{% url 'post:more_reples' 1234 %}".replace(/1234/,pk);
    $.ajax({
        url:url,
        dataType:'json',
        success:function(data){
            if(data.reples){
                $(".reple-list-"+pk+" >div ").html("")
                $this.css("display","none");
                for(var i=0; i<data.reples.length;i++){
                    $(".reple-list-"+pk+" > div").append("<p><span>"+data.reples[i].author_name+"&nbsp</span> "+data.reples[i].content+"</p>");
                }
            }
        }
    });
});

$(".reple-pointer").on("click",function(){
    var pk = $(this).attr("value");
    $(".reple-content-"+pk).focus();
});
{% endblock %}

django_instagram/post/templates/post/profile_form.html
{% extends 'base_home.html' %}
{% load staticfiles %}
{% block extrastyle %}{% static 'css/config.css' %}{% endblock %}
{% block content %}
<div class="menu">
                    <ul>
                        <li><a href="#"><p>프로필 편집</p></a></li>
                        <li><a href="{% url 'account:password_change' %}"><p>비밀번호 변경</p></a></li>
                        <li><a href="{% url 'account:logout' %}"><p>로그아웃</p></a></li>
                    </ul>
                </div>
                <div class="edit_area">
                    <form action="." method="post" enctype="multipart/form-data">{% csrf_token %}
                        {% if forms.errors %}
                             <script>
                                alert("프로필 변경에 실패했습니다. 다시 설정해주세요.");
                            </script>
                            {% endif %}
                        <table class="profile-table">

                            <tr>
                                <td><div><img src="{{ user.profile.avatar.url }}" alt="{{ user.username }}"></div></td>
                                <td>{{ user.username }}</td>
                            </tr>
                            <tr>
                                <td colspan="2">{{ form.errors }}</td>
                            </tr>
                            <tr>
                                <td>프로필 변경</td>
                                <td><input type="file" name="avatar" required></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td><input type="submit" valule="프로필 변경"></td>
                            </tr>
                        </table>
                    </form>
                </div>

{% endblock %}

django_instagram/post/templates/post/tag_list.html
{% extends 'base_home.html' %}
{% load staticfiles %}
{% block extrastyle %}{% static 'css/user_tag_post_list.css' %}{% endblock %}
{% block content %}
<div class="tag-area">
<h1>#{{ tag }}</h1>
    <p>{{ posts|length }}개의 결과</p>
</div>
<div class="post-area">
    <ul>
        {% for post in posts %}
        <li class="post tag-post">
            <a href="{{ post.get_absolute_url }}">
                <div>
                    <img src="{{ post.image.url }}" alt="image">
                    <div class="post_info">
                        <p>
                            <span></span>
                            <span>{{ post.reple_set.count }}</span>
                            <span></span>
                            <span>{{ post.like_set.count }}</span>
                        </p>
                    </div>
                </div>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

django_instagram/post/templates/post/user_post_list.html
{% extends 'base_home.html' %}
{% load staticfiles %}
{% block extrastyle %}{% static 'css/user_tag_post_list.css' %}{% endblock %}
{% block content %}
<div class="profile-area">
    <ul>
        <li>
            <div class="profile-area-img">
                <img src="{{  author.profile.avatar.url }}" alt="avatar">
            </div>
        </li>
        <li>
            <div class="profile-info">
                <span>{{ author.username }}</span>
                {% if author != user %}
                <button type="button" id="follow" class="{% if is_follow %} follow {% else %} folloing {% endif %}">{% if is_follow %}팔로우{% else %}팔로잉{% endif %}</button>
                {% else%}
                <a href="{% url 'account:password_change' %}"></a>
                {% endif %}

            </div>
            <div class="profile-post-info">
                <p>
                    게시물 {{ posts|length }}개 &nbsp;&nbsp;
                    <span class="follower_num">팔로우 {{ follower }}</span>&nbsp;&nbsp;
                    <span class="folloing_num"> 팔로잉 {{ folloing }}</span>
                </p>
            </div>
        </li>
    </ul>
</div>
<div class="post-area">
    <ul>
        {% for post in posts %}
        <li class="post">
            <a href="{{ post.get_absolute_url }}">
                <div>
                    <img src="{{ post.image.url }}" alt="image">
                    <div class="post_info">
                        <p>
                            <span></span>
                            <span>{{ post.reple_set.count }}</span>
                            <span></span>
                            <span>{{ post.like_set.count }}</span>
                        </p>
                    </div>
                </div>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}
{% block javascript %}
// 팔로우 기능
$("#follow").on("click",function(){
    $.ajax({
    url:'{% url "post:follow" author.username %}',
    dataType:'json',
    success: function(data){
        $(".follower_num").text("팔로우 "+data.follow_count);
        $("#follow").text(data.message_kr);
        $("#follow").attr("class",data.message);
    }
});
});
{% endblock %}